### ISSUE TITLE
Broken link to Robert C. Martin article

### ISSUE THREAD

**Issue by rhjones** [ga-wdi-boston/ruby-solid-study#56]
Link to '"Design Principles and Design Patterns" by Robert C. Martin' goes to a parked GoDaddy domain.

**Comment by rhjones** [comment]
Looks like http://mil-oss.org/resources/objectmentor_design-principles-and-design-patterns.pdf might be an acceptable alternative?

**Comment by raq929** [comment]
Fixed in PR #76
