### ISSUE TITLE
Inverted phrasing in discussion of LSP

### ISSUE THREAD

**Issue by kopius** [ga-wdi-boston/ruby-solid-study#61]
In study.md, under the heading `SOLID`, there is a sentence that reads:

``` md
For example, things we call "Vehicles" should behave like "Sedans", though the latter may
be more specific.
```

This phrasing seems to imply that `Vehicle` inherits behavior from `Sedan`, or that any Vehicle should be able to do anything that a Sedan can do. I would propose the following phrasing instead:

``` md
For example, things we call "Sedans" should behave like "Vehicles", though the former may
be more specific.
```

This phrasing implies the correct inheritance relationship between `Sedan` and `Vehicle`.

Please let me know if my understanding of the Liskov substitution principle here is incorrect.

**Comment by raq929** [comment]
Fixed in PR #76
